In [666]:
# !pip install pandas
# !pip install numpy
# !pip install matplotlib
# !pip install seaborn
# !pip install plotly
# !pip install scipy

### **Libraries Import**

In [667]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from scipy import stats

### **Data Load**

In [668]:
data = pd.read_csv("Dataset/financial_fraud_detection_&_risk_analytics.csv")

# **Data Cleaning & Preprocessing**

### **1. Data Structure**

In [669]:
data.head()

,Transaction_ID,Customer_ID,Contact,First_Name,Last_Name,Age,Gender,Account_Type,Transaction_Amount,Transaction_Type,...,Merchant_Category,Payment_Method,Device_Type,Login_Attempts,Transaction_Frequency,Risk_Score,Location,Previous_Fraud_History,Fraud_Status,KYC_Status
0,TXN200000,CUST1085,Nayantara Ben | 6344076115 | danilakshay@wagle...,Nayantara,Ben,21,Female,SAVINGS,7680.08,Transfer,...,Gaming,Gift Card,Desktop,5.0,6.0,14.0,"Bangalore, Karnataka, India",1,0,verified
1,TXN200001,CUST1003,Kaira Hans | 6136505587 | jivika52@yahoo.com,Kaira,Hans,55,M,NaN,3819.63,Withdrawal,...,Travel,Gift Card,Mobile,5.0,13.0,23.0,"Mumbai, Maharashtra, India",Yes,0,Certified
2,TXN200002,CUST1109,Biju Karnik | 6693989311 | dishanisuri@chaudhu...,Biju,Karnik,58,MALE,savings,9067.55,Withdrawal,...,Gaming,Debit Card,Mobile,NaN,7.0,61.0,"Kolkata, West Bengal, India",1,0,Certified
3,TXN200003,CUST1042,Fateh Chokshi | 6767303988 | fhegde@yahoo.com,Fateh,Chokshi,50,F,current,23749.88,Deposit,...,Investment,UPI,Mobile,1.0,4.0,36.0,"Ahmedabad, Gujarat, India",NO,0,Yes
4,TXN200004,CUST1022,Purab Butala | 7629748727 | bswaminathan@viswa...,Purab,Butala,28,M,savings,3437.26,Withdrawal,...,Entertainment,NaN,Mobile,4.0,13.0,75.0,"Chennai, Tamil Nadu, India",No,1,1

In [670]:
data.tail()

,Transaction_ID,Customer_ID,Contact,First_Name,Last_Name,Age,Gender,Account_Type,Transaction_Amount,Transaction_Type,...,Merchant_Category,Payment_Method,Device_Type,Login_Attempts,Transaction_Frequency,Risk_Score,Location,Previous_Fraud_History,Fraud_Status,KYC_Status
7432,TXN204104,CUST1103,Devansh Kuruvilla | 6667643690 | stuvansoni@si...,Devansh,Kuruvilla,65,Female,NaN,4150.97,Withdrawal,...,Insurance,UPI,Tablet,0.0,5.0,39.0,NaN,0,0,P
7433,TXN206638,CUST1021,Anahita Gopal | 6735034881 | rajprerak@yahoo.com,Anahita,Gopal,56,female,Current,2873.18,Withdrawal,...,Food,Net Banking,Desktop,7.0,3.0,4.0,"Hyderabad, Telangana, India",Unknown,0,n
7434,TXN204824,CUST1080,Sahil Jayaraman | 8991837720 | sodhianahita@ma...,Sahil,Jayaraman,36,M,Savings,4150.93,Withdrawal,...,Healthcare,UPI,Desktop,6.0,16.0,18.0,"Kolkata, West Bengal, India",YES,0,Yes
7435,TXN206696,CUST1047,Yuvraj Bera | 9774081712 | misha24@hotmail.com,Yuvraj,Bera,25,MALE,Current,13316.58,Deposit,...,Electronics,UPI,Desktop,7.0,11.0,28.0,"Chennai, Tamil Nadu, India",Yes,0,N
7436,TXN205635,CUST1093,Adira Mangat | 6311570307 | kanavkulkarni@gmai...,Adira,Mangat,38,F,Current,9679.21,Deposit,...,Travel,NaN,Mobile,7.0,15.0,66.0,"Mumbai, Maharashtra, India",No,0,No

In [671]:
data.shape

(7437, 21)

In [672]:
data.describe()

,Age,Transaction_Amount,Login_Attempts,Transaction_Frequency,Risk_Score,Fraud_Status
count,7437.000000,7.437000e+03,7394.000000,7417.000000,7252.000000,7437.000000
mean,45.120882,4.505099e+04,4.012172,10.452879,50.843905,0.079199
std,46.289858,5.612441e+05,2.576279,5.734128,30.659881,0.270067
min,-5.000000,1.257900e+02,0.000000,1.000000,-10.000000,0.000000
25%,27.000000,2.124600e+03,2.000000,5.000000,25.000000,0.000000
50%,43.000000,4.489120e+03,4.000000,10.000000,50.000000,0.000000
75%,58.000000,9.415840e+03,6.000000,15.000000,76.000000,0.000000
max,999.000000,1.000000e+07,8.000000,20.000000,250.000000,1.000000

In [673]:
data.describe(include="all")

,Transaction_ID,Customer_ID,Contact,First_Name,Last_Name,Age,Gender,Account_Type,Transaction_Amount,Transaction_Type,...,Merchant_Category,Payment_Method,Device_Type,Login_Attempts,Transaction_Frequency,Risk_Score,Location,Previous_Fraud_History,Fraud_Status,KYC_Status
count,7348,7304,7437,7437,7437,7437.000000,7437,7073,7.437000e+03,7043,...,7437,7110,6849,7394.000000,7417.000000,7252.000000,7167,7437,7437.000000,7437
unique,6746,117,203,87,102,NaN,7,5,NaN,4,...,9,7,4,NaN,NaN,NaN,12,9,NaN,24
top,TXN201789,CUST1095,Mohanlal Kadakia | 6915490795 | pbassi@gmail.com,Prisha,Bumb,NaN,Female,SAVINGS,NaN,Withdrawal,...,Travel,Gift Card,Mobile,NaN,NaN,NaN,"Ahmedabad, Gujarat, India",1,NaN,No
freq,2,81,83,196,209,NaN,1310,1438,NaN,1783,...,871,1079,1910,NaN,NaN,NaN,1353,864,NaN,649
mean,NaN,NaN,NaN,NaN,NaN,45.120882,NaN,NaN,4.505099e+04,NaN,...,NaN,NaN,NaN,4.012172,10.452879,50.843905,NaN,NaN,0.079199,NaN
std,NaN,NaN,NaN,NaN,NaN,46.289858,NaN,NaN,5.612441e+05,NaN,...,NaN,NaN,NaN,2.576279,5.734128,30.659881,NaN,NaN,0.270067,NaN
min,NaN,NaN,NaN,NaN,NaN,-5.000000,NaN,NaN,1.257900e+02,NaN,...,NaN,NaN,NaN,0.000000,1.000000,-10.000000,NaN,NaN,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,2.124600e+03,NaN,...,NaN,NaN,NaN,2.000000,5.000000,25.000000,NaN,NaN,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,43.000000,NaN,NaN,4.489120e+03,NaN,...,NaN,NaN,NaN,4.000000,10.000000,50.000000,NaN,NaN,0.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,58.000000,NaN,NaN,9.415840e+03,NaN,...,NaN,NaN,NaN,6.000000,15.000000,76.000000,NaN,NaN,0.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,999.000000,NaN,NaN,1.000000e+07,NaN,...,NaN,NaN,NaN,8.000000,20.000000,250.000000,NaN,NaN,1.000000,NaN

In [674]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7437 entries, 0 to 7436
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction_ID          7348 non-null   object
 1   Customer_ID             7304 non-null   object
 2   Contact                 7437 non-null   object
 3   First_Name              7437 non-null   object
 4   Last_Name               7437 non-null   object
 5   Age                     7437 non-null   int64
 6   Gender                  7437 non-null   object
 7   Account_Type            7073 non-null   object
 8   Transaction_Amount      7437 non-null   float64
 9   Transaction_Type        7043 non-null   object
 10  Transaction_Timestamp   7437 non-null   object
 11  Merchant_Category       7437 non-null   object
 12  Payment_Method          7110 non-null   object
 13  Device_Type             6849 non-null   object
 14  Login_Attempts          7394 non-null   float64
 15  Transaction_Frequency   7417 non-null   float64
 16  Risk_Score              7252 non-null   float64
 17  Location                7167 non-null   object
 18  Previous_Fraud_History  7437 non-null   object
 19  Fraud_Status            7437 non-null   int64
 20  KYC_Status              7437 non-null   object
dtypes: float64(4), int64(2), object(15)
memory usage: 1.2+ MB

### **2. Data Quality**

In [675]:
data.isnull().sum()

Transaction_ID             89
Customer_ID               133
Contact                     0
First_Name                  0
Last_Name                   0
Age                         0
Gender                      0
Account_Type              364
Transaction_Amount          0
Transaction_Type          394
Transaction_Timestamp       0
Merchant_Category           0
Payment_Method            327
Device_Type               588
Login_Attempts             43
Transaction_Frequency      20
Risk_Score                185
Location                  270
Previous_Fraud_History      0
Fraud_Status                0
KYC_Status                  0
dtype: int64

In [676]:
round(((data.isnull().sum()*100)/data.shape[0]),2)

Transaction_ID            1.20
Customer_ID               1.79
Contact                   0.00
First_Name                0.00
Last_Name                 0.00
Age                       0.00
Gender                    0.00
Account_Type              4.89
Transaction_Amount        0.00
Transaction_Type          5.30
Transaction_Timestamp     0.00
Merchant_Category         0.00
Payment_Method            4.40
Device_Type               7.91
Login_Attempts            0.58
Transaction_Frequency     0.27
Risk_Score                2.49
Location                  3.63
Previous_Fraud_History    0.00
Fraud_Status              0.00
KYC_Status                0.00
dtype: float64

In [677]:
data.nunique()

Transaction_ID            6746
Customer_ID                117
Contact                    203
First_Name                  87
Last_Name                  102
Age                         50
Gender                       7
Account_Type                 5
Transaction_Amount        6749
Transaction_Type             4
Transaction_Timestamp     6808
Merchant_Category            9
Payment_Method               7
Device_Type                  4
Login_Attempts               9
Transaction_Frequency       20
Risk_Score                 103
Location                    12
Previous_Fraud_History       9
Fraud_Status                 2
KYC_Status                  24
dtype: int64

### **3. Duplicates Remove**

In [678]:
duplicate_records = data.duplicated().sum()
duplicate_records

15

In [679]:
# string = "TXN20044"
# string[:3]

In [680]:
data = data.copy()

data["Transction_Series"] = data["Transaction_ID"].str[:3]
data["Transction_Num"] = data["Transaction_ID"].str[3:]

print(data[["Transaction_ID", "Transction_Series","Transction_Num"]])
print(data[["Transaction_ID", "Transction_Series","Transction_Num"]].dtypes)
data["Transction_Num"] = data["Transction_Num"].astype("Int64")
print(data[["Transaction_ID", "Transction_Series","Transction_Num"]].dtypes)

num_list = data["Transction_Num"].tolist()
print(type(num_list))
for i in range(len(num_list)):
      if pd.isna(num_list[i]):
            num_list[i] = num_list[i-1]+1

data["Transction_Series"] = data["Transction_Series"].fillna("TXN")
data["Transction_Num"] = pd.Series(num_list, dtype="Int64")

data["Transaction_ID"] = data["Transction_Series"] + data["Transction_Num"].astype("str")

     Transaction_ID Transction_Series Transction_Num
0         TXN200000               TXN         200000
1         TXN200001               TXN         200001
2         TXN200002               TXN         200002
3         TXN200003               TXN         200003
4         TXN200004               TXN         200004
...             ...               ...            ...
7432      TXN204104               TXN         204104
7433      TXN206638               TXN         206638
7434      TXN204824               TXN         204824
7435      TXN206696               TXN         206696
7436      TXN205635               TXN         205635

[7437 rows x 3 columns]
Transaction_ID       object
Transction_Series    object
Transction_Num       object
dtype: object
Transaction_ID       object
Transction_Series    object
Transction_Num        Int64
dtype: object
<class 'list'>

In [681]:
data = data.drop_duplicates()

In [682]:
data.shape

(7422, 23)

### **4. Fill Missing Values**

In [683]:
data.isnull().sum().sort_values(ascending=False)

Device_Type               588
Transaction_Type          394
Account_Type              364
Payment_Method            327
Location                  270
Risk_Score                185
Customer_ID               133
Login_Attempts             43
Transaction_Frequency      20
Transaction_ID              0
Transction_Series           0
KYC_Status                  0
Fraud_Status                0
Previous_Fraud_History      0
Merchant_Category           0
Transaction_Timestamp       0
Transaction_Amount          0
Gender                      0
Age                         0
Last_Name                   0
First_Name                  0
Contact                     0
Transction_Num              0
dtype: int64

In [684]:
data["Age"] = abs(data["Age"])
data["Risk_Score"] = abs(data["Risk_Score"])

In [685]:
data["Transaction_Frequency"] = data["Transaction_Frequency"].fillna(int(data["Transaction_Frequency"].mean()))
data["Login_Attempts"] = data["Login_Attempts"].fillna(int(data["Login_Attempts"].mean()))
data["Risk_Score"] = data["Risk_Score"].fillna(int(data["Risk_Score"].mean()))

data[["Payment_Method","Device_Type", "Account_Type", "Transaction_Type"]] = data[["Payment_Method","Device_Type", "Account_Type", "Transaction_Type"]].fillna("Unknown")

In [686]:
data.isnull().sum().sort_values(ascending=False)

Location                  270
Customer_ID               133
Transaction_ID              0
Payment_Method              0
Transction_Series           0
KYC_Status                  0
Fraud_Status                0
Previous_Fraud_History      0
Risk_Score                  0
Transaction_Frequency       0
Login_Attempts              0
Device_Type                 0
Merchant_Category           0
Transaction_Timestamp       0
Transaction_Type            0
Transaction_Amount          0
Account_Type                0
Gender                      0
Age                         0
Last_Name                   0
First_Name                  0
Contact                     0
Transction_Num              0
dtype: int64

### **5. Standardize Columns**

In [687]:
data["Gender"] = data["Gender"].str.lower()

gender_map = {
      "male": "Male",
      "m": "Male",
      "female": "Female",
      "f": "Female",
}

data["Gender"] = data["Gender"].replace(gender_map)

In [688]:
data["Previous_Fraud_History"] = data["Previous_Fraud_History"].str.lower()

prev_fraud_hstry = {
      "yes": "Yes",
      "y": "Yes",
      "1": "Yes",
      "no": "No",
      "n": "No",
      "0": "No",
}

data["Previous_Fraud_History"] = data["Previous_Fraud_History"].replace(prev_fraud_hstry)

In [689]:
data["KYC_Status"] = data["KYC_Status"].str.lower()

prev_fraud_hstry = {
      "1": "Verified",
      "v": "Verified",
      "verified": "Verified",
      "y": "Verified",
      "yes": "Verified",
      "0": "Rejected",
      "n": "Rejected",
      "no": "Rejected",
      "reject": "Rejected",
      "rejected": "Rejected",
      "r": "Rejected",
      "p": "Pending",
      "pending": "Pending",
      "certified": "Certified",
      "cerified": "Certified",
}

data["KYC_Status"] = data["KYC_Status"].replace(prev_fraud_hstry)

### **6. Split Columns**

In [690]:
data[["cnct_fullname", "Mobile_No", "Email"]] = data["Contact"].str.split("|", expand=True)

for col in ["cnct_fullname", "Mobile_No", "Email"]:
    data[col] = data[col].str.strip()

data["cnct_fname"] = data["cnct_fullname"].str.split().str[0]
data["cnct_lname"] = data["cnct_fullname"].str.split().str[1]

data[["cnct_fullname", "cnct_fname", "cnct_lname", "Mobile_No", "Email"]]

,cnct_fullname,cnct_fname,cnct_lname,Mobile_No,Email
0,Nayantara Ben,Nayantara,Ben,6344076115,danilakshay@wagle.com
1,Kaira Hans,Kaira,Hans,6136505587,jivika52@yahoo.com
2,Biju Karnik,Biju,Karnik,6693989311,dishanisuri@chaudhuri.com
3,Fateh Chokshi,Fateh,Chokshi,6767303988,fhegde@yahoo.com
4,Purab Butala,Purab,Butala,7629748727,bswaminathan@viswanathan.info
...,...,...,...,...,...
7432,Devansh Kuruvilla,Devansh,Kuruvilla,6667643690,stuvansoni@singhal.biz
7433,Anahita Gopal,Anahita,Gopal,6735034881,rajprerak@yahoo.com
7434,Sahil Jayaraman,Sahil,Jayaraman,8991837720,sodhianahita@majumdar.com
7435,Yuvraj Bera,Yuvraj,Bera,9774081712,misha24@hotmail.com
7436,Adira Mangat,Adira,Mangat,6311570307,kanavkulkarni@gmail.com

In [691]:
data[["Date", "Time"]] = data["Transaction_Timestamp"].str.split(" ", expand=True)

data["Date"] = data["Date"].str.replace("-", "/", regex=False)
data["Date"] = data["Date"].str.replace(":", "/", regex=False)
data["Time"] = data["Time"].str.replace("-", ":", regex=False)

data[["Transaction_Timestamp", "Date", "Time"]]

     Transaction_Timestamp        Date      Time
0      23-03-2025 18-34-30  23/03/2025  18:34:30
1         25-07-2024 14:28  25/07/2024     14:28
2      25:12:2024 05:55:49  25/12/2024  05:55:49
3         02-05-2026 19:40  02/05/2026     19:40
4         31-10-2025 22:35  31/10/2025     22:35
...                    ...         ...       ...
7432   08-12-2024 11-31-37  08/12/2024  11:31:37
7433      16-05-2025 13:53  16/05/2025     13:53
7434   20-08-2025 00-35-55  20/08/2025  00:35:55
7435      23-10-2025 22:12  23/10/2025     22:12
7436      19-11-2025 13:18  19/11/2025     13:18

[7422 rows x 3 columns]

### **7. Fill Unknown Value**

In [692]:
customer_cols = [
    "Customer_ID",
    "Contact",
    "Gender",
    "Account_Type",
    "Merchant_Category",
    "Location",
    "Previous_Fraud_History",
    "KYC_Status",
    "cnct_fullname",
]

df_customer_dtl = (
    data[customer_cols]
    .drop_duplicates(subset=["Customer_ID"])
    .reset_index(drop=True)
)

df_customer_dtl

,Customer_ID,Contact,Gender,Account_Type,Merchant_Category,Location,Previous_Fraud_History,KYC_Status,cnct_fullname
0,CUST1085,Nayantara Ben | 6344076115 | danilakshay@wagle...,Female,SAVINGS,Gaming,"Bangalore, Karnataka, India",Yes,Verified,Nayantara Ben
1,CUST1003,Kaira Hans | 6136505587 | jivika52@yahoo.com,Male,Unknown,Travel,"Mumbai, Maharashtra, India",Yes,Certified,Kaira Hans
2,CUST1109,Biju Karnik | 6693989311 | dishanisuri@chaudhu...,Male,savings,Gaming,"Kolkata, West Bengal, India",Yes,Certified,Biju Karnik
3,CUST1042,Fateh Chokshi | 6767303988 | fhegde@yahoo.com,Female,current,Investment,"Ahmedabad, Gujarat, India",No,Verified,Fateh Chokshi
4,CUST1022,Purab Butala | 7629748727 | bswaminathan@viswa...,Male,savings,Entertainment,"Chennai, Tamil Nadu, India",No,Verified,Purab Butala
...,...,...,...,...,...,...,...,...,...
113,CUST1065,Samarth Rout | 6416314667 | ubasu@hotmail.com,Male,savings,Travel,"Delhi, Delhi, India",No,Pending,Samarth Rout
114,CUST1007,Tiya Saha | 6027911967 | arnav27@hotmail.com,Female,savings,Healthcare,"Bangalore, Karnataka, India",unknown,Rejected,Tiya Saha
115,CUST1006,Mishti Andra | 8530876844 | farhan13@rout.com,Male,Current,Food,"Chennai, Tamil Nadu, India",No,Pending,Mishti Andra
116,CUST1114,Indrajit Chauhan | 7323959527 | nakul49@hotmai...,Male,SAVINGS,Fashion,"Pune, Maharashtra, India",Yes,Rejected,Indrajit Chauhan
117,CUST1048,Aarav Singh | 7034535593 | dishani63@kata-sank...,Male,Current,Healthcare,"Ahmedabad, Gujarat, India",No,Verified,Aarav Singh

In [693]:
cols = ["Account_Type", "Location", "Previous_Fraud_History", "KYC_Status"]

for col in cols:
    if col is not "Location":
        data[col] = data[col].str.title()
    data[col] = data[col].replace("Unknown", pd.NA)

<>:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\Krishnam Mavani\AppData\Local\Temp\ipykernel_992\757912390.py:4: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if col is not "Location":

In [694]:
lookup = (
    df_customer_dtl
    .drop_duplicates(subset=["cnct_fullname"])
    .set_index("cnct_fullname")
)

lookup

,Customer_ID,Contact,Gender,Account_Type,Merchant_Category,Location,Previous_Fraud_History,KYC_Status
cnct_fullname,,,,,,,,
Nayantara Ben,CUST1085,Nayantara Ben | 6344076115 | danilakshay@wagle...,Female,SAVINGS,Gaming,"Bangalore, Karnataka, India",Yes,Verified
Kaira Hans,CUST1003,Kaira Hans | 6136505587 | jivika52@yahoo.com,Male,Unknown,Travel,"Mumbai, Maharashtra, India",Yes,Certified
Biju Karnik,CUST1109,Biju Karnik | 6693989311 | dishanisuri@chaudhu...,Male,savings,Gaming,"Kolkata, West Bengal, India",Yes,Certified
Fateh Chokshi,CUST1042,Fateh Chokshi | 6767303988 | fhegde@yahoo.com,Female,current,Investment,"Ahmedabad, Gujarat, India",No,Verified
Purab Butala,CUST1022,Purab Butala | 7629748727 | bswaminathan@viswa...,Male,savings,Entertainment,"Chennai, Tamil Nadu, India",No,Verified
...,...,...,...,...,...,...,...,...
Samarth Rout,CUST1065,Samarth Rout | 6416314667 | ubasu@hotmail.com,Male,savings,Travel,"Delhi, Delhi, India",No,Pending
Tiya Saha,CUST1007,Tiya Saha | 6027911967 | arnav27@hotmail.com,Female,savings,Healthcare,"Bangalore, Karnataka, India",unknown,Rejected
Mishti Andra,CUST1006,Mishti Andra | 8530876844 | farhan13@rout.com,Male,Current,Food,"Chennai, Tamil Nadu, India",No,Pending
Indrajit Chauhan,CUST1114,Indrajit Chauhan | 7323959527 | nakul49@hotmai...,Male,SAVINGS,Fashion,"Pune, Maharashtra, India",Yes,Rejected
Aarav Singh,CUST1048,Aarav Singh | 7034535593 | dishani63@kata-sank...,Male,Current,Healthcare,"Ahmedabad, Gujarat, India",No,Verified

In [695]:
lookup.loc["Nirvaan Chada", "Customer_ID"]

nan

In [696]:
data["Customer_ID"] = data["Customer_ID"].fillna(
    data["cnct_fullname"].map(lookup["Customer_ID"])
)

for col in cols:
    data[col] = data[col].fillna(
        data["cnct_fullname"].map(lookup[col])
)

In [697]:
print(
    data[
        ["Customer_ID"] + cols
    ].isnull().sum()
)

Customer_ID                2
Account_Type               0
Location                  11
Previous_Fraud_History     0
KYC_Status                 0
dtype: int64

In [698]:
data[["City", "State", "Country"]] = data["Location"].str.split(",", expand=True)

for col in ["City", "State", "Country"]:
    data[col] = data[col].str.strip()

data[["City", "State", "Country"]]

           City        State Country
0     Bangalore    Karnataka   India
1        Mumbai  Maharashtra   India
2       Kolkata  West Bengal   India
3     Ahmedabad      Gujarat   India
4       Chennai   Tamil Nadu   India
...         ...          ...     ...
7432    Chennai   Tamil Nadu   India
7433  Hyderabad    Telangana   India
7434    Kolkata  West Bengal   India
7435    Chennai   Tamil Nadu   India
7436     Mumbai  Maharashtra   India

[7422 rows x 3 columns]

In [712]:
data.shape

(7355, 33)

In [707]:
data.isnull().sum().sort_values(ascending=False)

Country                   65
State                     33
Location                  11
City                      11
Customer_ID                2
Date                       0
cnct_lname                 0
cnct_fname                 0
Time                       0
Mobile_No                  0
cnct_fullname              0
Transction_Num             0
Transction_Series          0
KYC_Status                 0
Fraud_Status               0
Previous_Fraud_History     0
Email                      0
Transaction_ID             0
Transaction_Frequency      0
Login_Attempts             0
Device_Type                0
Payment_Method             0
Merchant_Category          0
Transaction_Timestamp      0
Transaction_Type           0
Transaction_Amount         0
Account_Type               0
Gender                     0
Age                        0
Last_Name                  0
First_Name                 0
Contact                    0
Risk_Score                 0
dtype: int64

In [709]:
data = data.dropna()

In [710]:
data.isnull().sum().sort_values(ascending=False)

Transaction_ID            0
Location                  0
State                     0
City                      0
Time                      0
Date                      0
cnct_lname                0
cnct_fname                0
Email                     0
Mobile_No                 0
cnct_fullname             0
Transction_Num            0
Transction_Series         0
KYC_Status                0
Fraud_Status              0
Previous_Fraud_History    0
Risk_Score                0
Customer_ID               0
Transaction_Frequency     0
Login_Attempts            0
Device_Type               0
Payment_Method            0
Merchant_Category         0
Transaction_Timestamp     0
Transaction_Type          0
Transaction_Amount        0
Account_Type              0
Gender                    0
Age                       0
Last_Name                 0
First_Name                0
Contact                   0
Country                   0
dtype: int64

In [711]:
data.shape

(7355, 33)

### **8. Fix Columns' Data Type**

### **9. Handles Errors & Outliers**

### **10. Lable Encode (Categorial -> Numeric)**

### **11. Drop Unused Columns & Rename Columns**

In [ ]:
# Created: Transction_Series, Transction_Num, cnct_fname, cnct_lname
# Default: Contact, Transaction_Timestamp, Location
# Un Used: First Name, Last Name, Country

# Rename: cnct_fullname-> Full Name

### **12. Save Clean Dataset**

In [716]:
data.to_csv("Dataset/cleaned.csv", index=False)